// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int nTimes = Integer.parseInt(args[0]);
	double randomNum;
	int counterMoreThan05 = 0;
	int counterLessThan05 = 0;
	for(int i=0; i<nTimes; i++){
		randomNum = Math.random();
		if( randomNum > 0.5 ){
			counterMoreThan05++;
		} else {
			counterLessThan05++;
		}
	}
	System.out.println("> 0.5: " +counterMoreThan05 +" times");
	System.out.println("<= 0.5: " +counterLessThan05 +" times");
	if(counterLessThan05!=0 && counterMoreThan05!=0){
		double ratio = (double)counterMoreThan05 /counterLessThan05;
		System.out.println("Ratio: " + ratio);
	}
	}
}
